---
channel: stable
addons:
  own2mqtt:
    repository: superinj/addon-own2mqtt
    target: own2mqtt
    image: superinj/{arch}-own2mqtt
  btalarm2mqtt:
    repository: superinj/addon-btalarm2mqtt
    target: btalarm2mqtt
    image: superinj/{arch}-btalarm2mqtt
